### ISSUE TITLE
Is J2534 the same for all cars?

### ISSUE THREAD

**Issue by brandonros** [Altenius/j2534-rs#1]
What kind of cable is needed to read J2534? I'm aware of OBD-II to DB9, OBD-II to DB25, OBD-II to USB, OBD-II to Ethernet.

Also, are there protection methods at play that prevent J2534 over CAN access in the wild?

**Comment by jcmnn** [comment]
J2534 is just a communication standard that all vehicle manufactures must follow. J2534 cables provide a DLL that provide an interface to a range of protocols such as CAN, ISO-TP.  This library is an interface to those DLLs.

These cables are typically used for reflashing PCMs or other modules because there are much cheaper alternatives if you just want diagnostics or datalogging.

 You can read more about it here http://www.drewtech.com/customers/diagaftmkt.html

The cables are overpriced though. Drewtech sells one for close to $400 and the cheapest one AFAIK is the Tactrix Openport 2.0 at $180.

**Comment by brandonros** [comment]
How does a cable provide a DLL? Can you elaborate on that? I don't fully understand.

https://www.newegg.com/Product/Product.aspx?Item=9SIADTU6650607

Why wouldn't a cable like that be all you need?

On Tactrix's OpenPort 2.0 listing, the say:

> Combined with our EcuFlash software, the OpenPort 2.0 is capable of reflashing a large number of newer Subaru and Mitsubishi vehicles, and support for other cars is in progress.

If "J2534 is just a communication standard that all vehicle manufactures must follow", why are there differences per manufacturer? At what layer do you start to see manufacturer protection?

**Comment by jcmnn** [comment]
The driver for the PassThru (J2534) device installs a DLL that is used to interface with the device. The SAE J2534 standard specifies the API that the DLL exposes. The functions it exposes can be found here: http://www.drewtech.com/support/passthru.html.

It provides a standard way to reprogram ECUs regardless of the underlying communication protocol. Manufacturers are required to comply with J2534 in their reprogramming software. This is so third parties like independent repair shops only need to have one PassThru device (like the OpenPort 2.0) to reprogram any vehicle.

This page explains it much better than I can: http://www.automotive-technology.co.uk/?p=2547

Unless you're creating tuning software, this probably is not what you are looking for. If you just want a way to communicate with the canbus, there are better cheaper ways. Unfortunately, it doesn't look like there are many rust libraries to communicate with any of those devices (like the bluetooth OBDII scanners). There is a socketcan library for socketcan devices but it only works with Linux.

**Comment by brandonros** [comment]
> http://www.drewtech.com/support/passthru.html

This is SAE J2534-1, do you have any plans to support SAE J2534-2?

> This is so third parties like independent repair shops only need to have one PassThru device (like the OpenPort 2.0) to reprogram any vehicle.

I don't think this is true though, is it? I don't like OpenPort 2.0 supports BMW/Mercedes/etc?

> Unless you're creating tuning software

I'm trying to understand if it is possible to speak directly to a car over J2534 without a passthru device.

> If you just want a way to communicate with the canbus

You can not reprogram ECUs just by communicating the the CANBus, correct?

**Comment by jcmnn** [comment]
> This is SAE J2534-1, do you have any plans to support SAE J2534-2?

It looks like J2534-2 just adds extra features to J2534-1 for non-emission vehicles. It probably adds a few flags so this library would "support" it. In the future, helper functions might be added.

> I'm trying to understand if it is possible to speak directly to a car over J2534 without a passthru device.

J2534 is not a protocol itself, it just specified the standard that PassThru devices must follow. Vehicles do not have any J2534-related code, because J2534 just provides a way to communicate with the vehicle using existing protocols like CAN.

> You can not reprogram ECUs just by communicating the the CANBus, correct?

Most ECUs made in the past two decades are programmed through the CAN bus only.

**Comment by brandonros** [comment]
http://shop.dimsport.us/my-genius-handheld-device/

This is a J2534 PassThru device from what I can tell. I guess I had the (very not smart) idea of getting Linux going with a connection from OBD-II to DB25 and reading traffic from there, bypassing the PassThru device. It sounds like I'd be in a world of hurt trying to follow J2534 myself without a PassThru device. Is that correct? It seems the general approach is to just buy a PassThru device and play with it from there.

> > This is so third parties like independent repair shops only need to have one PassThru device (like the OpenPort 2.0) to reprogram any vehicle.

> I don't think this is true though, is it? I don't like OpenPort 2.0 supports BMW/Mercedes/etc?

Can you comment on whether or not this is true to your knowledge?

Thank you for being so knowledgable and friendly.

**Comment by jcmnn** [comment]
If the OpenPort does not support those manufacturers, then it is probably because they use their own connector separate from the OBD-II port for reflashing and there are probably other PassThru devices that do support them. It can probably still read/write to the CAN bus, though.

Since you are using Linux, I would recommend using a socketcan device if you want to monitor the can bus. I can personally recommend https://canable.io/ as it is what I use (and I have used it to reprogram my ECU). It does not come with an OBD-II connector though so you have to either connect the CAN high and low to the pins on the OBD-II connector on the car (I connected the wires with tape but it was a pita to keep it from falling out) or you can get an OBD-II like this: https://www.sparkfun.com/products/9911 and solder wires to the can high/low.

You can use that with the socketcan crate too

**Comment by brandonros** [comment]
Let me get this last detail clear. I apologize for my lack of detailed knowledge on the subject.

J2534 is a standard *passthru devices* (not vehicles) must follow. It specifies an interface on how a computer can speak to a passthru device.

From there, on a manufacturer specific level, the passthru device then speaks one of these protocols:

* SAE J1850 PWM (Pulse Width Modulation)
* SAE J1850 VPW (Variable Pulse Width)
* ISO 9141-2
* ISO 14230 KWP2000 (Keyword Protocol 2000)
* ISO 15765 CAN (In either 250 or 500 kbit/s)

over the OBD-II port.

So, if I got a passthru device, I could theoretically sniff the CAN traffic it sends + receives to/from the vehicle to see how it reads/writes an ECU, yeah?

So, I don't need the J2534 standard at all. I need a passthru device and the accompanying software it comes with to interface with the device (which uses J2534), but I need the CAN commands sent.

Does this sound right? 

>  I have used it to reprogram my ECU

Can you give some insight/details on how you used your CANable to reprogram your ECU? Any thoughts on how it compares to this: https://www.tindie.com/products/Muted/canalyze/ ?

**Comment by jcmnn** [comment]
> J2534 is a standard _passthru devices_ (not vehicles) must follow. It specifies an interface on how a computer can speak to a passthru device.
> 
> From there, on a manufacturer specific level, the passthru device then speaks one of these protocols:
>    ...
> over the OBD-II port.

Yes

> So, if I got a passthru device, I could theoretically sniff the CAN traffic it sends + receives to/from the vehicle to see how it reads/writes an ECU, yeah?

Yes, but it would be easier to use something else (like the canable). Also, J2534 is Windows-only.

> So, I don't need the J2534 standard at all. I need a passthru device and the accompanying software it comes with to interface with the device (which uses J2534), but I need the CAN commands sent.
> Does this sound right?

Yes.

> > I have used it to reprogram my ECU
> 
> Can you give some insight/details on how you used your CANable to reprogram your ECU? Any thoughts on how it compares to this: https://www.tindie.com/products/Muted/canalyze/ ?

They have the same functionality and both use socketcan. The CANalyze would be easier to connect to the OBD-II port since you can use an OBD-II <-> DB9 cable. 


As for reprogramming it, I used a python library [like this](https://python-can.readthedocs.io/en/3.0.0/interfaces/socketcan.html) (I don't remember which one exactly) to send/receive CAN frames. Reprogramming is different for every ECU but in my case it used [UDS](https://en.wikipedia.org/wiki/Unified_Diagnostic_Services) + some Mazda-specific stuff.

**Comment by brandonros** [comment]
> The CANalyze would be easier to connect to the OBD-II port since you can use an OBD-II <-> DB9 cable.

My only fear is not capturing traffic from the OBD-II port on non-CAN pins using an OBD-II <-> DB9 cable. If you check the OBD-II pins (https://en.wikipedia.org/wiki/On-board_diagnostics), do you agree there is a chance some manufacturers could flash over pins that are not captured by a OBD-II <-> DB9 cable, or am I wrong?

Say I have to use the CANable instead, what do I have to do to run pins from the OBD-II ports into the CANable?

**Comment by jcmnn** [comment]
Yes, some manufacturers will use protocols other than CAN for reprogramming, but it is uncommon afaik. ECUs use a seed and key algorithm to secure certain services such as reprogramming, so you will not be able to reprogram it just by sniffing the session. You would need to find the algorithm which would require reverse engineering the firmware on the ECU.

This book is a decent intro to car/ECU hacking: http://opengarages.org/handbook/.

For using the CANable, you need to connect the CAN high & low pins on the CANable to the high and low pins on the OBD-II port (which you can see from the pin diagram) with a lead. I used a copper wire and held it onto the port with tape.

**Comment by brandonros** [comment]
What information can you share about the seed/key algorithm process from the perspective of what you went through when flashing your ECU?

**Comment by jcmnn** [comment]
The ECU generates a random seed when sent a security request, then uses the algorithm to generate a key. It  responds with the seed, then I generate the key using the same algorithm. I send a key request with the key, and it checks to see if it's equal to the key it generated. If it is, the secured services like reprogramming are unlocked.

**Comment by brandonros** [comment]
Is your code where you did this available?

How large was the seed/key on your ECU? Small enough to brute force? I've heard it's up to 1024 bytes on some cars now?

**Comment by jcmnn** [comment]
Often times there is a timer or a set amount of tries before the seed is reset so brute forcing isn't really an option.

I think the seed is around 8 bytes: https://github.com/LibreTuner/LibreTuner/blob/master/src/udsauthenticator.cpp

**Comment by brandonros** [comment]
Awesome. I was just going to ask if UDS was involved.

How did you figure that out? Did you have the ARM instructions of CPU and you read the assembly? Has anybody ever done like a ECU virtual machine?

**Comment by jcmnn** [comment]
Yes, I disassembled the firmware to find the security access subroutines. It uses the SuperH architecture, though. The microcontroller manufacturer (Renesas) has a simulator but I have not had luck using it. You would have to simulate each engine sensor.

**Comment by brandonros** [comment]
How did you acquire the firmware?

**Comment by jcmnn** [comment]
Mazda used to have it publicly available.

**Comment by brandonros** [comment]
I see your LibreTuner project (which looks awesome by the way) plans to support RX-8s. Could you give a high level overview on some of the challenges you face in trying to use your current codebase to support RX-8s? What is different?

**Comment by jcmnn** [comment]
I built it to be modular so supporting more platforms will be easy. It uses the same download protocol and adding maps is as easy as adding an entry in the definition files. The biggest difference is that the RX-8 uses a wildly different protocol to flash, so the new flash protocol will need to be added. But no changes will need to be made to the codebase, only additions.

**Comment by brandonros** [comment]
>  The biggest difference is that the RX-8 uses a wildly different protocol to flash

What protocol does it use? Is it CAN or K2000?

**Comment by jcmnn** [comment]
CAN. The difference is that it requires a secondary bootloader to be uploaded before flashing.

**Comment by brandonros** [comment]
Sorry to keep pestering you with questions. Please feel free to not answer. I am just beyond fascinated with your wealth of information.

Can you go a bit more into detail on where that secondary bootloader comes into play?

Ignition is on, OBD-II -> CAN device is connected, start UDS diagnostics session, pass seed/key security mode, go to read/write memory regions and what happens?

**Comment by brandonros** [comment]
Following up on the wealth of information that you are. :)

**Comment by jcmnn** [comment]
There is a special UDS service for uploading the secondary bootloader. It is used to upload the bootloader and then boot into it. It contains the routines for receiving the actual program from the CAN bus and flashing it. "Secondary bootloader" is kind of a misnomer because it's just a new program that's uploaded to RAM and executed instead of the main one stored on flash (but it is not stored permanently).

**Comment by DevX-Cipher** [comment]
does this support bluetooth yet
